secrets:
    sops:
        age_key: ENC[AES256_GCM,data:Ep4BMrNB1wAR3LC6GgNR54N+OVSk/s2UTxEsHfmfv5Z5M+nmhM6f74h5JBhHZLMg+MtKdl3VVHl1YX+yKJq137P2rbab0WK/HA5l,iv:jp6RtbpHaAeIyg25JHwVeC9Dj/0z0zIUMUUTzy9mk8w=,tag:Ro6i5hN2nP88j3blEpcyWA==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:KJ949iNhOLtog+3hQzkm8fI6AiSoNoJjLsiD79F06RElaTn3A79i/EG7ZRgjzPtfHQ==,iv:JtyAUkMvXJ+89uvFMTm+Vnaez+J1KMZpZ4lXyY58pHc=,tag:0xWh6H/ekEnqYx0ZT9Ngew==,type:str]
            username: ENC[AES256_GCM,data:8ttmYBVc,iv:qAszBRVAxhDpD9I388FNP4FgnTz4cUppvuITOHm7exQ=,tag:8s/Ow90J9oZnnkJY77g77w==,type:str]
            password: ENC[AES256_GCM,data:B6LmcnBJxduPQLMIb9u0AeBMPzCgiAPPoQnTWNuUJQ5nY2lU0r7IY+6/WSGSqDXDxbJ1eZWlrl/hXXdHPUrekqw8zxbcYSRIkw==,iv:mN8HwVnXCgob0TEq0aNOvMINMepebKiIUy7oZltLjE0=,tag:kqzzumBHS6Z+iafwtarF2g==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:mZJWgNfyTRVb6Bk=,iv:0UHM1lYjnf5eCxDSZbdpaih7aZ09+jRdXgquPjApqcE=,tag:k68ZLhn2yAFUcbI6xyU8mg==,type:str]
                password: ENC[AES256_GCM,data:n+0LQ0A3BaYuQSubfYgA1zBUOAKlT5X+1VUNT8cy5ODFMgztWAKq6g==,iv:qUITWgpo6xIbBtkNaZIZO7gdUTz2vmaRAQG8LgppdiI=,tag:OL9DctXWwGjMXQhVhjYJSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV0dkSWdOTndKWEpFQ0ll
            Y2Y1MHpmSnN5c2N2eEt1SDgwK0pYMUxlMm13ClNQWUtGcSszekxxbXV3anhLTXov
            ZXQrVjdwRy9PbUxBMkd0NFhpaFJqWFEKLS0tIE51SWpIbEo4SzBneUhENFJuQWNV
            VEZUQzJwM2htc2QwK2RmOVJTdmpOZmMKbN1nTGxnWbK4X6ZtExMz7ksshwR8PcUt
            kbA710PfpPI1mlBu3tnGzVyfACY+5OgL0xkFC1Xyj3BchSXHk9ct7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:05:10Z"
    mac: ENC[AES256_GCM,data:7NKoW4AazbCwj1GVkpogHmtR9mheIEhjxOCGKMBWHfNmShrhzDBseSbD5vhBkKePwoWfPSiMwCeAlFEuwt8uI+BoxkayC+YlMN7N68N2+pjnhwvY5YnKpdpPI/v+F056Hnb0YPbd5VCUZEH27dZH3+EnIyj1Ls9Sh4jo6Kp86uI=,iv:wk1v6Q3CQ7wSDQbBxppdKIDqMw+flhBcqASyM+GgEkE=,tag:GwU0R4PbUoMhE+f2MVySkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
